### PR TITLE
conditionally copy database.sql to the container

### PR DESCRIPTION
**Pull request by oysteingy**
Conditionally copy the file 'database.sql' to the container, if the file exists.  This approach seems a bit easier to perform than mounting the dump file to the nav container as /database.sql.

### CODE REVIEW

**Comment by oysteingy** [comment]
```
if [ "${NOINITDB}" -eq 0 ] && ! (psql -l | grep -q "$DB"); then
    if [ -f "/database.sql" ]; then
                log "Initializing a new database schema from /database.sql"
                navsyncdb -c -r /database.sql
```

Ensures that the database will only be synced if there is no database named 'nav'

**Review by lunkwill42 — COMMENTED** [review]
This change doesn't concern containers - it copies `database.sql` into the image that is being built. All containers ever created from this image will now have a copy of `database.sql` in it. That doesn't make sense to me at all.

You might also run the risk of uploading an image that contains sensitive production data to the public DockerHub :-P

**Comment by oysteingy** [comment]
Your milage may vary.  README.md states 'you can do so by mounting the dump file to the nav container as /database.sql' but there is no instructions for how to modify docker-compose.yml to achieve this.  This PR was intended to simplify getting a 
 testing/development installation up and running.  I don't make that many containers out of a single image so I'm not so concerned about disk usage ;)  

If you have a large production environment you'd better consider other options for importing your database dump. 

Regarding risk of uploading sensitive stuff to DockerHub, this will also affect LDAP/database/SMTP credentials.

**Comment by lunkwill42** [comment]
> Your milage may vary. README.md states 'you can do so by mounting the dump file to the nav container as /database.sql' but there is no instructions for how to modify docker-compose.yml to achieve this. 

That's pretty straightforward. If you don't know how, I can easily insert a comment into `docker-compose.yml` that shows how to do it. But, you might only want to do it the first time the container i started, not every time, so some ekstra arguments to the `docker-compose` command might be more suitable.

> This PR was intended to simplify getting a testing/development installation up and running. I don't make that many containers out of a single image so I'm not so concerned about disk usage ;)

I get that. But this repo is also used to produce official images that are uploaded to the DockerHub, which is why I'm hesitant to accept patches that potentially bake private information into the created images.

> Regarding risk of uploading sensitive stuff to DockerHub, this will also affect LDAP/database/SMTP credentials.

I cannot see that these credentials are baked into the image. Can you? If they are, it's a bug.

**Comment by oysteingy** [comment]
> I cannot see that these credentials are baked into the image. Can you? If they are, it's a bug.

Well, it will depends I guess.

For settings that are not environment variables ( part of .conf-files ) like LDAP, I see no easy way to configure NAV without adding webfront.conf to the image. Maybe it's doable with a volume, but that will be a quite a rewrite.

PS:  I'll cancel the PR, seems like this are better of implemented by other means.

**Comment by lunkwill42** [comment]
> For settings that are not environment variables ( part of .conf-files ) like LDAP, I see no easy way to configure NAV without adding webfront.conf to the image. Maybe it's doable with a volume, but that will be a quite a rewrite.

You don't need volumes, per se. You can easily bind-mount single files to a container, just as with `database.sql` - no need to bake them into the image.

I have no qualms about accepting PRs that make more bits of NAV configurable via environment variables - that would be the most appropriate option for contatiner deployment :-) ATM, the implementation makes environment variables mostly just out of the settings required to get NAV running (i.e. `nav.conf`).

**Pull request closed without merging**
