### PR TITLE
Add SELinux labels and volume for Apache2 config

### PR DESCRIPTION
**Pull request by oysteingy**
Add SELinux labels for all volumes.

### CODE REVIEW

**Review by lunkwill42 — COMMENTED** [review]
Thanks a bunch @oysteingy - Looks good to me :-) I just didn't quite catch what the `/etc/apache2` is needed for?

**Comment by oysteingy** [comment]
The apache2 volume was created to solve a problem that occurred during the Docker build - 
`RUN a2dissite 000-default; a2ensite nav-site` 

`Step 22/29 : RUN a2ensite nav-site
Enabling site nav-site.
find: '/var/lib/apache2/site/enabled_by_admin/000-default': No such file or directory`

This left 000-default.conf in /etc/apache2/sites-enabled, and hence was not the config in nav-site not applied as 000-default was read before nav-site.conf.   

Creating a volume for the /etc/apache2 directory solved the problem, as the problem appeared to me as a file system issue.

**Comment by lunkwill42** [comment]
Strangeness. Starting entirely from scratch (pulled all the base images from the Dockerhub and dropped mye cache), I can't reproduce this. This is what I get:

```
Step 21/28 : RUN a2dissite 000-default; a2ensite nav-site
 ---> Running in 6af431ca4f98
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
Enabling site nav-site.
To activate the new configuration, you need to run:
  service apache2 reload
```

What's your host OS?

**Comment by oysteingy** [comment]
Hi, 

I'm using CentOS Linux release 7.6.1810 (Core).  Not able to reproduce this on my Mac.

$ docker-compose -v
docker-compose version 1.18.0, build 8dd22a9
$ docker -v
Docker version 1.13.1, build b2f74b2/1.13.1

I reproduced this on a clean install on the same platform:

Step 21/28 : RUN a2dissite 000-default; a2ensite nav-site
 ---> Running in 14c3c007f40f

Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload
Enabling site nav-site.
find: '/var/lib/apache2/site/enabled_by_admin/000-default': No such file or directory
To activate the new configuration, you need to run:
  service apache2 reload
 ---> 2603fca74024

(..)

$ docker exec -it  navcontainer_nav_1 /bin/bash                                                                                                                                                                                                                                                                                                         
root@106cf4143681:/# ls  -alh /etc/apache2/sites-enabled/
ls: cannot access '/etc/apache2/sites-enabled/000-default.conf': No such file or directory
total 0
drwxr-xr-x. 1 root root 49 Sep 19 10:55 .
drwxrwxr-x. 1 root root 26 Sep 18 08:30 ..
??????????? ? ?    ?     ?            ? 000-default.conf
lrwxrwxrwx. 1 root root 32 Sep 19 10:55 nav-site.conf -> ../sites-available/nav-site.conf

root@106cf4143681:/# cat /etc/apache2/sites-enabled/000-default.conf 
cat: /etc/apache2/sites-enabled/000-default.conf: No such file or directory


root@106cf4143681:/# curl http://localhost | more
bla bla 
 <p>
                Debian's Apache2 default configuration is different from the
                upstream default configuration, and split into several files optimized for
                interaction with Debian tools
bla bla

**Comment by lunkwill42** [comment]
Still not sure what good the apache config volume is, other than it fixes some voodoo problem you're experiencing - since the config isn't meant to be touched while running or to be shared with anything else - but it doesn't break anything for anyone else, so I'm going to accept it :-)

**Pull request merged**
